# alpha、beta、main 三个分支
# 在 alpha 本地开发、提交到 beta 后自动构建作为测试用（但不发布）
# 再合并到 main（不自动构建），本地切换到 main 分支，使用 npm version 打标签，然后推送（自动构建并发布）

name: CI
on:
  push:
    tags:
      - 'v*.*.*' # 需用 if 限制只对 main 分支生效
  pull_request:
    branches:
      - beta
    types:
      - closed
env:
  GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.merged == true || startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    outputs:
      pkg_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: 设置 node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: 构建
        run: pnpm build
      - name: 获取 package.json 版本
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        shell: bash
      - name: 查看版本
        run: echo ${{ steps.get_version.outputs.version }}
        shell: bash
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ steps.get_version.outputs.version }}
          path: |
            release/${{ steps.get_version.outputs.version }}/*.exe
            release/${{ steps.get_version.outputs.version }}/*.dmg
            release/${{ steps.get_version.outputs.version }}/*.yml
          retention-days: 5 # 保留5天

  Release:
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    needs: Build
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ needs.Build.outputs.pkg_version }}
      - name: 查看构建产物
        run: ls
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.exe
            release/*.dmg
            release/*.yml
